import StudySessionList from './StudySessionList';
import { Suspense } from 'react';
import Loading from '../loading';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
	title: 'Study Sessions',
	description: 'Generated by create next app',
};

export default function StudySessions() {
	return (
		<main className="StudySession container">
			<div className="d-flex justify-content-between align-items-center">
				<h2 className="text-primary">Study Sessions</h2>{' '}
				<Link href="/study-sessions/create" className="btn btn-primary">
					New Study Session
				</Link>
			</div>

			<Suspense fallback={<Loading />}>
				<StudySessionList />
			</Suspense>
		</main>
	);
}
